source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '9.0'

target 'ObjCDemo' do
 	pod 'SCSafariPageController', :path => '../'
end

target 'SwiftDemo' do
	pod 'SCSafariPageController', :path => '../'
end
