source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ObjCDemo' do
 	pod 'SCSafariPageController', :path => '../'
end

target 'SwiftDemo' do
	pod 'SCSafariPageController', :path => '../'
end
